ai:
  label: AI
  permalink: /ai
  description: Artificial Intelligence and machine learning

agile:
  label: Agile
  permalink: /agile
  description: Agile development methodology

automation:
  label: Automation
  permalink: /automation
  description: Process automation and workflow tools

algorithm:
  label: Algorithm
  permalink: /algorithm
  description: Algorithms and computational methods

algorithms:
  label: Algorithms
  permalink: /algorithms
  description: Algorithms and computational methods

architecture:
  label: Architecture
  permalink: /architecture
  description: Software architecture and system design

backend:
  label: Backend
  permalink: /backend
  description: Backend development and server-side technologies

blog:
  label: Blog
  permalink: /blog
  description: General blog posts

complexity:
  label: Complexity
  permalink: /complexity
  description: Software complexity and complexity management

crawlab:
  label: Crawlab
  permalink: /crawlab
  description: Crawlab web scraping platform

deepseek:
  label: DeepSeek
  permalink: /deepseek
  description: DeepSeek AI models and technology

csharp:
  label: C#
  permalink: /csharp
  description: C# programming language

da:
  label: Data Analytics
  permalink: /data-analytics
  description: Data analysis and data science

data-analysis:
  label: Data Analysis
  permalink: /data-analysis
  description: Data analysis and data science

devops:
  label: DevOps
  permalink: /devops
  description: Development operations and CI/CD

docusaurus:
  label: Docusaurus
  permalink: /docusaurus
  description: Docusaurus static site generator

distributed-systems:
  label: Distributed Systems
  permalink: /distributed-systems
  description: Distributed computing and system architecture

frontend:
  label: Frontend
  permalink: /frontend
  description: Frontend development and user interfaces

github:
  label: GitHub
  permalink: /github
  description: GitHub platform and version control

golang:
  label: Go
  permalink: /golang
  description: Go programming language

javascript:
  label: JavaScript
  permalink: /javascript
  description: JavaScript programming language

llm:
  label: LLM
  permalink: /llm
  description: Large Language Models

machine-learning:
  label: Machine Learning
  permalink: /machine-learning
  description: Machine learning and AI techniques

nextjs:
  label: Next.js
  permalink: /nextjs
  description: Next.js React framework

project-management:
  label: Project Management
  permalink: /project-management
  description: Agile methodologies and project management

react:
  label: React
  permalink: /react
  description: React framework and library

software-engineering:
  label: Software Engineering
  permalink: /software-engineering
  description: Software engineering principles and practices

technical-management:
  label: Technical Management
  permalink: /technical-management
  description: Technical leadership and engineering management

testing:
  label: Testing
  permalink: /testing
  description: Software testing and quality assurance

translation-needed:
  label: Translation Needed
  permalink: /translation-needed
  description: Articles that need English translation

typescript:
  label: TypeScript
  permalink: /typescript
  description: TypeScript programming language

vue:
  label: Vue
  permalink: /vue
  description: Vue.js framework

vercel:
  label: Vercel
  permalink: /vercel
  description: Vercel deployment platform and tools

systems-design:
  label: Systems Design
  permalink: /systems-design
  description: System architecture and design patterns

prompt-engineering:
  label: Prompt Engineering
  permalink: /prompt-engineering
  description: Prompt engineering and AI interaction design

open-source:
  label: Open Source
  permalink: /open-source
  description: Open source projects and community

publishing:
  label: Publishing
  permalink: /publishing
  description: Content publishing and management

web-crawler:
  label: Web Crawler
  permalink: /web-crawler
  description: Web crawling and data scraping

rag:
  label: RAG
  permalink: /rag
  description: Retrieval-Augmented Generation

vector-search:
  label: Vector Search
  permalink: /vector-search
  description: Vector databases and semantic search

productivity:
  label: Productivity
  permalink: /productivity
  description: Developer productivity and workflow optimization

development-tools:
  label: Development Tools
  permalink: /development-tools
  description: Tools and utilities for software development

workflow:
  label: Workflow
  permalink: /workflow
  description: Development workflows and processes

methodology:
  label: Methodology
  permalink: /methodology
  description: Software development methodologies and approaches

requirements-engineering:
  label: Requirements Engineering
  permalink: /requirements-engineering
  description: Requirements analysis and specification techniques

development-workflow:
  label: Development Workflow
  permalink: /development-workflow
  description: Structured approaches to software development processes

enterprise:
  label: Enterprise
  permalink: /enterprise
  description: Enterprise-grade software solutions and architecture

agents:
  label: Agents
  permalink: /agents
  description: AI agents and autonomous systems

context-management:
  label: Context Management
  permalink: /context-management
  description: Context handling and management in AI systems

data-infrastructure:
  label: Data Infrastructure
  permalink: /data-infrastructure
  description: Data infrastructure and platform engineering

data-architecture:
  label: Data Architecture
  permalink: /data-architecture
  description: Data architecture design and enterprise data modeling
